# Generated by Django 5.0.3 on 2024-03-10 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=150, verbose_name='Активность')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сопутствующая ривычка',
                'verbose_name_plural': 'Сопутствующие привычки',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='Место выполнения')),
                ('usual_time', models.DateTimeField(verbose_name='Время выполнения')),
                ('activity', models.CharField(max_length=100, verbose_name='Активность')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Признак приятности')),
                ('periodicity', models.CharField(choices=[('weekly', 'Раз в неделю'), ('daily', 'Каждый день')], default='daily', max_length=6, verbose_name='Переодичность')),
                ('fee', models.CharField(blank=True, max_length=150, null=True, verbose_name='Вознагрождение')),
                ('time_to_complete', models.PositiveIntegerField(default=1, verbose_name='Время выполнения')),
                ('is_published', models.BooleanField(default=False, verbose_name='Публикация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habit.relatedhabit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
